trigger: none

stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      PackageName: "@azure/communication-identity"
      ServiceDirectory: communication
      MatrixFilters:
        - DependencyVersion=^$
      CloudConfig:
        Public:
          SubscriptionConfigurations:
            - $(sub-config-azure-cloud-test-resources)
            - $(sub-config-communication-services-cloud-test-resources-test)
        Int:
          SubscriptionConfiguration: $(sub-config-communication-int-test-resources)
      Clouds: Public,Int
